hive  -e  "
use ods;
create table  ODS_CDR_BGDT_G_M 
(

      ACCT_MONTH   string   comment   '账期',
      SYS_SVC_TYPE   string   comment   '业务类型',
      SEQ_NO   string   comment   '序列号',
      TIME   string   comment   '时间戳',
      MESSAGE_ID   string   comment   '消息id',
      SP_ID   string   comment   'Spid',
      SERVICE_ID   string   comment   '业务id',
      CP_ID   string   comment   'Cpid',
      CONTENT_ID   string   comment   '"计费类型0：不计费,1：免费,2：按次计费,3：包月收取,4:按变量计费,"',
      ACCESS_NO   string   comment   '接入号码',
      SERVICE_TYPE   string   comment   '业务种类',
      SOURCEDEVICE_TYPE   string   comment   'SOURCEDEVICE_TYPE',
      SOURCEDEVICE_ID   string   comment   'SOURCEDEVICE_ID',
      CDR_TYPE   string   comment   '话单类型',
      PRODUCT_ID   string   comment   '使用费资费产品id（已经废掉了）',
      SPC_PRODUCT_ID   string   comment   '使用费资费产品id（相当于PRODUCT_ID）',
      SP_PRODUCT_ID   string   comment   '租费产品id （相当于PRM_ProductID）也就是用户的主套餐产品编号',
      ORDER_METHOD   string   comment   'ORDER_METHOD',
      PUSH_ID   string   comment   '计价单位类型，当ChargeType=4是有效。1：栅格数2：属性数3：栅格·属性·次4：用户数',
      OAMDN   string   comment   '计费号码',
      DAMDN   string   comment   '计费号码',
      FAMDN   string   comment   '计费号码',
      USER_TYPE   string   comment   '用户类型',
      START_TIME   string   comment   '始话时间',
      END_TIME   string   comment   '截止时间',
      TIME_SEC   string   comment   '计价单位数量，当ChargeType=4是有效。本次消费产生的计价单位数量',
      INPUT_OCTETS   decimal(20,3)   comment   'INPUT_OCTETS',
      OUTPUT_OCTETS   decimal(20,3)   comment   'OUTPUT_OCTETS',
      FEE_POINT   string   comment   'FEE_POINT',
      BILL_TYPE   string   comment   'BILL_TYPE',
      IFEE1   decimal(20,3)   comment   '信息费一批金额',
      RESV1   string   comment   'RESV1',
      RESV2   string   comment   'RESV2',
      ISRATE   string   comment   '7代表不需要二批',
      IMSI   string   comment   'IMSI',
      FILE_TYPE   string   comment   '文件类型',
      FILE_NO   string   comment   '文件标识',
      VNUMBER   decimal(20,3)   comment   'VNUMBER',
      SVC_NAME   string   comment   'SVC_NAME',
      SUBSCRIPTION_ID   string   comment   '用户标识',
      SERVICE_NUMR   string   comment   '计费号码',
      ACCOUNT_ID   string   comment   '账户标识',
      PART_ID   string   comment   '分区标识',
      SVC_TYPE   string   comment   '用户业务大类',
      REGION_ID   string   comment   '地区标识',
      USAGE_CASE   string   comment   'USAGE_CASE',
      USAGE_TYPE   string   comment   'USAGE_TYPE',
      USAGE_CLASS   string   comment   'USAGE_CLASS',
      CLASS_OF_SERVICE_CODE   string   comment   'CLASS_OF_SERVICE_CODE',
      CFEE   decimal(20,3)   comment   'CFEE',
      LFEE   decimal(20,3)   comment   'LFEE',
      IFEE   decimal(20,3)   comment   '二批信息费金额',
      MFEE   decimal(20,3)   comment   'MFEE',
      TFEE   decimal(20,3)   comment   'TFEE',
      DIS_CFEE   decimal(20,3)   comment   'DIS_CFEE',
      DIS_LFEE   decimal(20,3)   comment   'DIS_LFEE',
      DIS_IFEE   decimal(20,3)   comment   'DIS_IFEE',
      CFEE_TIMES   decimal(20,3)   comment   'CFEE_TIMES',
      LFEE_TIMES   decimal(20,3)   comment   'LFEE_TIMES',
      IFEE_TIMES   decimal(20,3)   comment   'IFEE_TIMES',
      MFEE_TIMES   decimal(20,3)   comment   'MFEE_TIMES',
      TFEE_TIMES   decimal(20,3)   comment   'TFEE_TIMES',
      CFEE_SUBJECT   string   comment   'CFEE_SUBJECT',
      LFEE_SUBJECT   string   comment   'LFEE_SUBJECT',
      IFEE_SUBJECT   string   comment   '二批信息费科目',
      MFEE_SUBJECT   string   comment   'MFEE_SUBJECT',
      TFEE_SUBJECT   string   comment   'TFEE_SUBJECT',
      PACKAGE_ID   string   comment   'PACKAGE_ID',
      PRODUCT_CLASS   string   comment   'PRODUCT_CLASS',
      ORIGINAL_FILE   string   comment   '原始文件名',
      LATE_LINK   string   comment   'LATE_LINK',
      CAL_TIME   string   comment   '批价时间',
      AUDI_STR   string   comment   '优惠批价轨迹',
      VARIAN_STR   string   comment   '免费量优惠轨迹',
      RERATE_CNT   string   comment   '重批标识',
      TIMESTAMPS   string   comment   '入库时间'
            )
comment '[MASTER_FIELD:B域,LEVEL:ODS层,DATA_FIELD:详单域,DATASUB_FIELD:ODS_CDR_BGDT_G_M]'
PARTITIONED BY (MONTH_PART STRING comment '月份分区')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS RCFILE;
"