hive  -e  "
use ods;
create table  ODS_CDR_GUPA_M  
(

      ACCT_MONTH   string   comment   '统计月份',
      FILE_TYPE   string   comment   'FILE_TYPE',
      FILE_SN   string   comment   'FILE_SN',
      RECORD_TYPE   string   comment   '漫入类型',
      CDR_FEE_CODE   string   comment   'CDR_FEE_CODE',
      VISIT_AREA_CODE   string   comment   '访问区域',
      VISIT_LOCAL_NET   string   comment   'VISIT_LOCAL_NET',
      ORG_TRM_ID   string   comment   '主被叫',
      SELF_NUMBER   string   comment   '本方号码',
      SELF_AREA_CODE   string   comment   '本方区域',
      SELF_LOCAL_NET   string   comment   '本地网络',
      SELF_BUSI_DISTRICT   string   comment   'SELF_BUSI_DISTRICT',
      SELF_USER_TYPE   string   comment   '本方用户类型',
      SELF_SERVICE_CLASS   string   comment   'SELF_SERVICE_CLASS',
      SELF_REGION_CODE   string   comment   '本方代码',
      NET_TYPE   string   comment   '网络类型',
      CALL_TYPE   string   comment   '通话类型',
      OPP_NUMBER   string   comment   '对方号码',
      OPP_NUMBER_SUFFIX   string   comment   '对方号码前缀',
      OPP_AREA_CODE   string   comment   '对方区域',
      OPP_LOCAL_NET   string   comment   '对方网络',
      OPP_BUSI_DISTRICT   string   comment   'OPP_BUSI_DISTRICT',
      OPP_NUMBER_TYPE   string   comment   '对方号码类型',
      OPP_DEALER_CODE   string   comment   '对方运营商',
      OPP_SERVICE_CLASS   string   comment   '对方服务类型',
      OPP_REGION_CODE   string   comment   '对方所属区域',
      SERVICE_CODE   string   comment   '业务类型',
      CHARGE_DATE   string   comment   '通话时间',
      CHARGE_TIME   string   comment   '通话时段',
      CALL_DURATION   int   comment   '通话时长',
      SELF_MSC_ID   string   comment   'SELF_MSC_ID',
      SELF_LAC_ID   string   comment   'SELF_LAC_ID',
      SELF_CELL_ID   string   comment   'SELF_CELL_ID',
      OPP_MSC_ID   string   comment   'OPP_MSC_ID',
      OPP_LAC_ID   string   comment   'OPP_LAC_ID',
      OPP_CELL_ID   string   comment   'OPP_CELL_ID',
      IN_TRUNK   string   comment   'IN_TRUNK',
      OUT_TRUNK   string   comment   'OUT_TRUNK',
      TRUNK_TYPE   string   comment   'TRUNK_TYPE',
      BASE   decimal(20,3)   comment   '基本费',
      LAND   decimal(20,3)   comment   '长途费',
      SS   decimal(20,3)   comment   'SS',
      OTHER   decimal(20,3)   comment   'OTHER',
      BASE_TIMES   decimal(20,3)   comment   '基本计费时长',
      LAND_TIMES   decimal(20,3)   comment   '长途计费时长',
      SS_TIMES   decimal(20,3)   comment   'SS_TIMES',
      OTHER_TIMES   decimal(20,3)   comment   'OTHER_TIMES',
      PAY_FLAG   string   comment   '付费标志',
      TELE_SERVICE   string   comment   'TELE_SERVICE',
      BEARER_SERVICE   string   comment   'BEARER_SERVICE',
      SS_CODE   string   comment   'SS_CODE',
      IMSI   string   comment   'IMSI',
      THIRD_NUMBER   string   comment   'THIRD_NUMBER',
      MSRN   string   comment   'MSRN',
      BOUNDARY_CELL_FLAG   string   comment   'BOUNDARY_CELL_FLAG',
      SAME_CITY_FLAG   string   comment   'SAME_CITY_FLAG',
      CARD_NO   string   comment   'CARD_NO',
      FILE_NAME   string   comment   'FILE_NAME',
      RESERVE   string   comment   'RESERVE',
      INSERT_DATE   string   comment   '经分数据入库时间',
      SYS_TYPE   string   comment   '漫入用户使用2G/3G网络',
      SPEED   string   comment   'SPEED',
      HOT_BILLING   string   comment   'HOT_BILLING'
            )
comment '[MASTER_FIELD:B域,LEVEL:ODS层,DATA_FIELD:详单域,DATASUB_FIELD:月漫入详单表]'
PARTITIONED BY (MONTH_PART STRING comment '月份分区')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS RCFILE;
"