hive  -e  "
use ods;
create table  ODS_CHL_CIM_COMM_FOR_BAS_M
(

      ACCT_MONTH   string   comment   'ACCT_MONTH',
      COMM_SN   string   comment   'COMM_SN',
      PAYCYCLE   string   comment   'PAYCYCLE',
      BILLINGCYCLID   string   comment   'BILLINGCYCLID',
      SUBSCRBID   string   comment   'SUBSCRBID',
      SVCNUM   string   comment   'SVCNUM',
      SVCID   string   comment   'SVCID',
      TOTALFEE   decimal(20,3)   comment   'TOTALFEE',
      ARREARFEE   decimal(20,3)   comment   'ARREARFEE',
      COMMFEE   decimal(20,3)   comment   'COMMFEE',
      COMMITEM   string   comment   'COMMITEM',
      FEE   decimal(20,3)   comment   'FEE',
      FEETYPE   string   comment   'FEETYPE',
      MODID   string   comment   'MODID',
      RULEID   string   comment   'RULEID',
      DEALPROCESS   string   comment   'DEALPROCESS',
      AGENTID   string   comment   'AGENTID',
      VPNID   string   comment   'VPNID',
      ERRORCODE   string   comment   'ERRORCODE',
      REMARK   string   comment   'REMARK',
      OPTYPE   string   comment   'OPTYPE',
      COUNTYID   string   comment   'COUNTYID',
      AREAID   string   comment   'AREAID',
      OPENCYCLE   string   comment   'OPENCYCLE',
      SETT_TYPE   string   comment   'SETT_TYPE',
      COMM_TYPE   string   comment   'COMM_TYPE',
      FRZ_SN   string   comment   'FRZ_SN',
      CREATE_DATE   string   comment   'CREATE_DATE',
      DEPT_ID   string   comment   'DEPT_ID',
      COMM_SRC   string   comment   'COMM_SRC',
      SUBJECTID   string   comment   'SUBJECTID',
      AUDITOR_1   string   comment   'AUDITOR_1',
      AUDIT_TIME_1   string   comment   'AUDIT_TIME_1',
      AUDITOR_2   string   comment   'AUDITOR_2',
      AUDIT_TIME_2   string   comment   'AUDIT_TIME_2',
      AUDITOR_3   string   comment   'AUDITOR_3',
      AUDIT_TIME_3   string   comment   'AUDIT_TIME_3',
      BASICNUM   string   comment   'BASICNUM',
      AGENTNO   string   comment   'AGENTNO',
      AGENTNAME   string   comment   'AGENTNAME',
      CUSTNAME   string   comment   'CUSTNAME',
      ACCTID   string   comment   'ACCTID',
      SVCTP   string   comment   'SVCTP',
      MAIN_PRCPLNID   string   comment   'MAIN_PRCPLNID',
      USERGRP   string   comment   'USERGRP',
      USERGRP2   string   comment   'USERGRP2',
      USERTYPE   string   comment   'USERTYPE',
      USERTYPE2   string   comment   'USERTYPE2',
      SETT_SN   string   comment   'SETT_SN',
      OPENDATE   string   comment   'OPENDATE',
      CLOSEDATE   string   comment   'CLOSEDATE',
      BRAND_ID   string   comment   'BRAND_ID',
      SUB_BRAND_ID   string   comment   'SUB_BRAND_ID',
      AUDIT_SN   string   comment   'AUDIT_SN',
      PAY_ID   string   comment   'PAY_ID',
      CHANNEL_NAME   string   comment   'CHANNEL_NAME',
      MOD_NAME   string   comment   'MOD_NAME',
      QUANTITY   string   comment   'QUANTITY',
      KEY_SOURCE_TYPE_CD   string   comment   'KEY_SOURCE_TYPE_CD',
      PRODUCT_KIND_ID   string   comment   'PRODUCT_KIND_ID',
      LOCATION_ID   string   comment   'LOCATION_ID',
      CONTRACT_ID   string   comment   'CONTRACT_ID'
            )
comment '[MASTER_FIELD:B域,LEVEL:ODS层,DATA_FIELD:渠道域,DATASUB_FIELD:ODS_CHL_CIM_COMM_FOR_BAS_M]'
PARTITIONED BY (MONTH_PART STRING comment '月份分区')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS RCFILE;
"
