hive -e "use src;
CREATE TABLE AGENT_CHANNEL_DEVELOPER(
CHANNEL_ID         STRING,
CHANNEL_LEVEL      STRING,
STATION            STRING,
TEAM_CHANNEL_ID    STRING,
WORK_ADDRESS       STRING,
RESIDENCE_FLAG     STRING,
RESIDENCE          STRING,
BASIC_INTEGRAL     STRING,
EMPLOYEE_CODE      STRING,
USER_ID            STRING,
LINK_PHONE         STRING,
MOBILE_PHONE       STRING,
REMARK             STRING,
EMPLOYEE_NAME      STRING,
EMP_YN             STRING,
FLAG               STRING
)
COMMENT '日联通用工性质表'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS TEXTFILE;"