hive -e "use src;
CREATE TABLE BDS_IMSI_PREFIX(  
LOWER_IMSI_PREFIX    STRING COMMENT 'LOWER_IMSI_PREFIX',  
UPPER_IMSI_PREFIX    STRING COMMENT 'UPPER_IMSI_PREFIX',
LOCAL_NET            STRING COMMENT 'LOCAL_NET',
AREA_CODE            STRING COMMENT 'AREA_CODE' ,       
DEALER_CODE          STRING COMMENT 'DEALER_CODE',      
SERVICE_CLASS        STRING COMMENT 'SERVICE_CLASS',    
USER_TYPE            STRING COMMENT 'USER_TYPE',   
EFF_DATE             STRING COMMENT 'EFF_DATE' ,       
EXP_DATE             STRING COMMENT 'EXP_DATE',         
COMMENTS             STRING COMMENT 'COMMENTS'         
)
COMMENT '地区运营商编码映射表'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS TEXTFILE;"
