hive -e "use src;
CREATE TABLE BMS_BUSI_DEF(
BUSI_ID               STRING,
BUSI_DESC             STRING,
AUDIT_TYPE            STRING,
REMARK                STRING,
MTD_REMARK            STRING,
BUSI_ID_TYPE          STRING,
CAN_TRANSACT          STRING,
NEED_DEVELOP_INFO     STRING,
PARENT_BUSI_ID        STRING,
BMS_ACCEPT_TYPE       STRING,
BUSI_PRORITY          STRING,
OPTYPE_ID             STRING,
PRIO_LEVEL            STRING
)
COMMENT 'нч'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS TEXTFILE;"