hive -e  "use src
CREATE TABLE SRC.BMS_ROAM_DETAIL(  
ACCT_DATE STRING COMMENT '账期',
SETTLE_ITEM_CODE STRING COMMENT 'SETTLE_ITEM_CODE',
ROAM_IN STRING COMMENT 'ROAM_IN',
ROAM_OUT STRING COMMENT 'ROAM_OUT'
)
COMMENT '抽取日结算数据'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS TEXTFILE;"