hive -e "use src;
 CREATE TABLE BUSINESS_OPERATE(
 ID                   STRING,
 BUSINESS_ID          STRING,
 BUSINESS_KIND        STRING,
 SO_VIEW              STRING,
 OPERATE_TYPE         STRING,
 QUERY_FLAG           STRING,
 DEL_FLAG             STRING,
 USER_STATE_CONFIG    STRING,
 COMMIT_STATE         STRING,
 SO_STATE             STRING,
 FEE_CHECK            STRING,
 EXTEND_FLAG          STRING,
 STATE                STRING,
 REMARKS              STRING,
 REMOVE_BUSINESS_ID   STRING,
 QC_FLAG              STRING,
 IS_STATE_UPDATE      STRING,
 FLOW_TEMPLATE_CODE   STRING,
 EVENT_CODE           STRING
 )
 COMMENT '业务操作表'
 ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
 STORED AS TEXTFILE;"