hive -e "use src;
CREATE TABLE CRM_LOCATION_SALE_RELAT(
ROW_ID          STRING,
LOCATION_ID     STRING,
SALE_ID         STRING,
STATE           STRING,
INSERT_DATE     STRING,
EXPIRE_DATE     STRING,
REMARKS         STRING
)
COMMENT '楼宇销售对应关系'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS TEXTFILE;"