hive -e "use src;
CREATE TABLE GRP_INDUSTRY_KIND_CONFIG_NEW(  
INDUSTRY_TYPE_ID   STRING COMMENT 'INDUSTRY_TYPE_ID',
INDUSTRY_KIND_ID   STRING COMMENT 'INDUSTRY_KIND_ID',
INDUSTRY_KIND_NAME STRING COMMENT 'INDUSTRY_KIND_NAME',
INSERT_DATE        STRING COMMENT 'INSERT_DATE',
STAUTS             STRING COMMENT 'STAUTS',
REMARK             STRING COMMENT 'REMARK'     
)
COMMENT '集团行业小类的码表'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS TEXTFILE;"