hive -e "use src;
CREATE TABLE GRP_PM_PRODUCT(  
ACCT_MONTH         STRING COMMENT 'ACCT_MONTH', 
PRODUCT_ID         STRING COMMENT 'PRODUCT_ID',
PRODUCT_NAME       STRING COMMENT 'PRODUCT_NAME',
PRODUCT_DESC       STRING COMMENT 'PRODUCT_DESC',
PRODUCT_DETAIL     STRING COMMENT 'PRODUCT_DETAIL',
PRODUCT_TYPE       STRING COMMENT 'PRODUCT_TYPE',
BRAND_ID           STRING COMMENT 'BRAND_ID',
CREATE_TIME        STRING COMMENT 'CREATE_TIME',
INSERT_DATE        STRING COMMENT 'INSERT_DATE'
)
COMMENT '1.1.92	¼¯¿ÍÌ×²Í'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS TEXTFILE;"