hive -e "use src;
CREATE TABLE PM_LABEL_DEF(
PM_LABEL_ID          STRING,
PM_LABEL_NAME        STRING,
CREATE_TIME          STRING,
CHANGE_TIME          STRING,
OP_OPERATOR_ID       STRING
)
COMMENT 'нч'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS TEXTFILE;"