hive -e "use src;
CREATE TABLE PM_PE_VALUE(
PE_ID              STRING,
PE_VALUE           STRING,
PE_VALUE_DESC      STRING
)
COMMENT '1.1.48	产品相关编码'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '001' 
STORED AS TEXTFILE;"