hive -e "use src;
CREATE TABLE RPT_DEPT_HALL(
DEPT_ID             STRING,
DEPT_NAME           STRING,
HALL_ID             STRING,
HALL_NAME           STRING,
COUNTYID            STRING,
STATUS              STRING,
CREATE_DATE         STRING,
OPERATOR_ID         STRING,
CHG_DATE            STRING,
CHG_OPERATOR_ID     STRING
)
COMMENT '缴费相关码表'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS TEXTFILE;"