hive -e "use src;
CREATE TABLE SYS_SVC_FEATURE(
SVC_TYPE                 STRING,
SVC_FEAT_NAME            STRING,
SVC_FEAT_LEVEL           STRING,
PE_ID                    STRING,
SVC_FEAT_DESC            STRING,
SVC_FEAT_VALUE_MIN       STRING,
SVC_FEAT_VALUE_MAX       STRING,
SVC_FEAT_VALUE_DEFAULT   STRING,
SVC_FEAT_UNIT            STRING,
SVC_FEAT_TYPE            STRING,
SVC_FEAT_STATISTIC       STRING,
SVC_FEAT_ORDER           STRING,
SVC_FEAT_CATEGORY        STRING,
SVC_FEAT_PARENT          STRING
)
COMMENT 'нч'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS TEXTFILE;"