hive -e "use src;
CREATE TABLE SYS_PARAMETERS(
REGION_ID        STRING,
SVC_TYPE         STRING,
PARAM_ID         STRING,
PARAM_DATATYPE   STRING,
PARAM_VALUE      STRING,
PARAM_DESC       STRING,
OPER_DATE        STRING,
OPER_ID          STRING,
PARAM_TYPE       STRING
)
COMMENT '日系统常量配置表'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS TEXTFILE;"