hive -e "use src;
CREATE TABLE SYS_SVC_FEATVAL(
SVC_TYPE         STRING,
SVC_FEAT_NAME    STRING,
SVC_FEAT_VALUE   STRING,
SVC_FEAT_VDESC   STRING
)
COMMENT '可以请教代一菱'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS TEXTFILE;"