hive -e "use src;
CREATE TABLE TAB_XCOUNTY(
XCOUNTY_ID     STRING,
XCOUNTY_NAME   STRING,
AREAID         STRING
)
COMMENT '客户维系系统对特定集团用户所打的地域'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS TEXTFILE;"