hive -e "use src;
CREATE TABLE TAB_COUNTY(
COUNTYID           STRING,
AREAID             STRING,
COUNTYNAME         STRING,
COUNTYID_SHORT     STRING,
HQ_COUNTYID        STRING
)
COMMENT 'ÇøÏØÂë±í'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS TEXTFILE;"