hive -e "use src;
CREATE TABLE TAB_DEPT_TYPE(
DEPT_TYPE          STRING,
NAME               STRING,
DEPT_PTYPE         STRING,
DEPT_CTYPE         STRING,
BUSIFEE_TYPE       STRING,
RIGHT_TYPE         STRING
)
COMMENT '部门类型表'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS TEXTFILE;"