hive -e "use src;
CREATE TABLE UCS_CONTRANT_USER(
PRODUCT_ID           STRING,
CONTRANT_USER_ID     STRING,
CUSTOMER_ID          STRING,
SERVICE_TYPE         STRING,
DOCID                STRING,
SUBSCRIPTION_ID      STRING,
ACCOUNT_ID           STRING,
REGION_ID            STRING,
PRESENT_AMOUNT       STRING,
PAY_RULE_ID          STRING,
CREATE_DATE          STRING,
ACTIVE_DATE          STRING,
INACTIVE_DATE        STRING,
OPTOPERTOR_ID        STRING,
OP_REGION_ID         STRING,
OFFICE_ID            STRING,
LAST_PAY_MONTH       STRING,
REMARK               STRING
)
COMMENT '日参加固网在网有礼活动的客户对应的移网侧用户'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS TEXTFILE;"