hive -e "use src;
CREATE TABLE ZB_ACTION_PLAN(
ACTPLANID          STRING,
OP_TYPE            STRING,
ACTPLANDESCRIBE    STRING,
ACTPROTPER         STRING,
PRODUCTID          STRING,
RESOURCESTYPE      STRING,
RESOURCESRELE      STRING,
RESOURCESBRAND     STRING,
RESOURCESMODEL     STRING,
RESOURCESFEE       STRING,
ALLOWANCEFEE       STRING,
STOREDFEE          STRING,
PRESENTEDFEE       STRING,
THAWPRO            STRING,
THAWMON            STRING,
TOTALSALEFEE       STRING,
MONTHLOWESTFEE     STRING,
DEPFEE             STRING,
LOCAL_SCHEME_ID    STRING,
SCHEMEID           STRING
)
COMMENT '合约计划编码'
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS TEXTFILE;"