#/bin/bash

#业务逻辑输入参数，此处很重要，需要根据实际业务情况认真设定！！！！ 
v_month=$1

echo "
insert overwrite table ODS.ODS_M_U_BI_INF_CONT_M partition (month_part='$v_month') 
    SELECT 
'$v_month', 
USER_NO,
DEVICE_NUMBER,
QUERY_LAB,
CONSULT_LAB,
BUSINESS_LAB,
TROUBLE_LAB,
COMPLAINT_LAB,
OTHER_LAB,
THR_QUERY_LAB,
THR_CONSULT_LAB,
THR_BUSINESS_LAB,
THR_TROUBLE_LAB,
THR_COMPLAINT_LAB,
THR_OTHER_LAB,
SIX_QUERY_LAB,
SIX_CONSULT_LAB,
SIX_BUSINESS_LAB,
SIX_TROUBLE_LAB,
SIX_COMPLAINT_LAB,
SIX_OTHER_LAB,
YEAR_QUERY_LAB,
YEAR_CONSULT_LAB,
YEAR_BUSINESS_LAB,
YEAR_TROUBLE_LAB,
YEAR_COMPLAINT_LAB,
YEAR_OTHER_LAB,
INSERT_DATE
FROM SRC.TB_MK_BI_INF_CONT_M;
"


