CREATE TABLE ODS_BUS_BMS_BUSI_DEF_D  (
ACCT_MONTH            STRING COMMENT 'ACCT_MONTH',       
DAY_ID                STRING COMMENT 'DAY_ID',           
BUSI_ID               STRING COMMENT 'BUSI_ID',          
BUSI_DESC             STRING COMMENT 'BUSI_DESC',        
AUDIT_TYPE            STRING COMMENT 'AUDIT_TYPE',       
REMARK                STRING COMMENT 'REMARK',           
MTD_REMARK            STRING COMMENT 'MTD_REMARK',       
BUSI_ID_TYPE          STRING COMMENT 'BUSI_ID_TYPE',     
CAN_TRANSACT          STRING COMMENT 'CAN_TRANSACT',     
NEED_DEVELOP_INFO     STRING COMMENT 'NEED_DEVELOP_INFO',
PARENT_BUSI_ID        STRING COMMENT 'PARENT_BUSI_ID',   
BMS_ACCEPT_TYPE       STRING COMMENT 'BMS_ACCEPT_TYPE',  
BUSI_PRORITY          STRING COMMENT 'BUSI_PRORITY',     
OPTYPE_ID             STRING COMMENT 'OPTYPE_ID',        
PRIO_LEVEL            STRING COMMENT 'PRIO_LEVEL'        
   
)
COMMENT ''
PARTITIONED BY (MONTH_PART STRING COMMENT '月份分区',
DAY_PART STRING COMMENT '日期分区')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS RCFILE;