CREATE TABLE ODS_CHL_AI_MOD_CONFIG_D(
ACCT_MONTH      STRING COMMENT 'ACCT_MONTH',   
DAY_ID          STRING COMMENT 'DAY_ID',       
MOD_ID          STRING COMMENT 'MOD_ID',       
MOD_TYPE        STRING COMMENT 'MOD_TYPE',     
SVC_ID          STRING COMMENT 'SVC_ID',       
MOD_NAME        STRING COMMENT 'MOD_NAME',     
EFF_DATE        STRING COMMENT 'EFF_DATE',     
EXP_DATE        STRING COMMENT 'EXP_DATE',     
MOD_PRIORITY    STRING COMMENT 'MOD_PRIORITY', 
PRIORITY        STRING COMMENT 'PRIORITY',     
AREA_ID         STRING COMMENT 'AREA_ID',      
MOD_STATE       STRING COMMENT 'MOD_STATE',    
COMMENTS        STRING COMMENT 'COMMENTS',     
SUB_SYSTEM_ID   STRING COMMENT 'SUB_SYSTEM_ID',
CREATOR         STRING COMMENT 'CREATOR',      
CREATE_TIME     STRING COMMENT 'CREATE_TIME',  
UPDATOR         STRING COMMENT 'UPDATOR',      
UPDATE_TIME     STRING COMMENT 'UPDATE_TIME',  
STATE           STRING COMMENT 'STATE',        
VERIFY_ID       STRING COMMENT 'VERIFY_ID'     
           
)
COMMENT '从CRM2抽取佣金数据'
PARTITIONED BY (MONTH_PART STRING COMMENT '月份分区',
DAY_PART STRING COMMENT '日期分区')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS RCFILE;
