CREATE TABLE ODS_PRD_PM_LABEL_DEF_D(
ACCT_MONTH       STRING COMMENT 'ACCT_MONTH',   
DAY_ID           STRING COMMENT 'DAY_ID',       
PM_LABEL_ID      STRING COMMENT 'PM_LABEL_ID',  
PM_LABEL_NAME    STRING COMMENT 'PM_LABEL_NAME',
CREATE_TIME      STRING COMMENT 'CREATE_TIME',  
CHANGE_TIME      STRING COMMENT 'CHANGE_TIME',  
OP_OPERATOR_ID   STRING COMMENT 'OP_OPERATOR_ID'

)
COMMENT ''
PARTITIONED BY (MONTH_PART STRING COMMENT '月份分区',
DAY_PART STRING COMMENT '日期分区')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS RCFILE;