CREATE TABLE ODS_PUB_RPT_DEPT_HALL_D(
ACCT_MONTH           STRING COMMENT 'ACCT_MONTH', 
DAY_ID               STRING COMMENT 'DAY_ID',     
DEPT_ID              STRING COMMENT 'DEPT_ID',    
DEPT_NAME            STRING COMMENT 'DEPT_NAME',  
HALL_ID              STRING COMMENT 'HALL_ID',    
HALL_NAME            STRING COMMENT 'HALL_NAME',  
COUNTYID             STRING COMMENT 'COUNTYID',   
STATUS               STRING COMMENT 'STATUS',     
CREATE_DATE          STRING COMMENT 'CREATE_DATE',
OPERATOR_ID          STRING COMMENT 'OPERATOR_ID',
CHG_DATE             STRING COMMENT 'CHG_DATE',   
CHG_OPERATOR_ID      STRING COMMENT 'CHG_OPERATOR_ID' 
)
COMMENT ''
PARTITIONED BY (MONTH_PART STRING COMMENT '月份分区',
DAY_PART STRING COMMENT '日期分区')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS RCFILE;