CREATE TABLE ODS_PRD_RULE_DEFAULT_PRD_D(
ACCT_MONTH       string comment 'ACCT_MONTH',     
DAY_ID           string comment 'DAY_ID',         
FROM_PRODUCT_ID  string comment 'FROM_PRODUCT_ID',
TO_PRODUCT_ID    string comment 'TO_PRODUCT_ID'   
)
COMMENT ''
PARTITIONED BY (MONTH_PART STRING COMMENT '月份分区',
DAY_PART STRING COMMENT '日期分区')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS RCFILE;