CREATE TABLE ODS_CDR_BMS_ROAM_DETAIL_D  (
ACCT_MONTH         STRING COMMENT 'ACCT_MONTH',      
DAY_ID             STRING COMMENT 'DAY_ID',          
ACCT_DATE          STRING COMMENT 'ACCT_DATE',       
SETTLE_ITEM_CODE   STRING COMMENT 'SETTLE_ITEM_CODE',
ROAM_IN            BIGINT COMMENT 'ROAM_IN',         
ROAM_OUT           BIGINT COMMENT 'ROAM_OUT'         
)
COMMENT ''
PARTITIONED BY (MONTH_PART STRING COMMENT '月份分区',
DAY_PART STRING COMMENT '日期分区')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS RCFILE;