CREATE TABLE ODS_RES_PARAM_MOBILE_TYPE_D  (
ACCT_MONTH          STRING COMMENT 'ACCT_MONTH',      
DAY_ID              STRING COMMENT 'DAY_ID',          
MOBILE_MODEL        STRING COMMENT 'MOBILE_MODEL',    
MODEL_NAME          STRING COMMENT 'MODEL_NAME',      
MOBILE_BRAND        STRING COMMENT 'MOBILE_BRAND',    
REPAIR_TIME         STRING COMMENT 'REPAIR_TIME',     
RETURN_BACK_TIME    STRING COMMENT 'RETURN_BACK_TIME',
SVC_TYPE            STRING COMMENT 'SVC_TYPE',        
MOBILE_KIND         STRING COMMENT 'MOBILE_KIND'      

)
COMMENT ''
PARTITIONED BY (MONTH_PART STRING COMMENT '月份分区',
DAY_PART STRING COMMENT '日期分区')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS RCFILE;