CREATE TABLE ODS_PUB_DISTRICT_D  (
ACCT_MONTH          STRING COMMENT 'ACCT_MONTH',        
DAY_ID              STRING COMMENT 'DAY_ID',            
DISTRICT_ID         STRING COMMENT 'DISTRICT_ID',       
NAME                STRING COMMENT 'NAME',              
DISTRICT_TYPE_ID    STRING COMMENT 'DISTRICT_TYPE_ID',  
BUSINESS_AREA_ID    STRING COMMENT 'BUSINESS_AREA_ID',  
PARENT_DISTRICT_ID  STRING COMMENT 'PARENT_DISTRICT_ID',
AREA_CODE           STRING COMMENT 'AREA_CODE',         
STATE               STRING COMMENT 'STATE',             
REMARKS             STRING COMMENT 'REMARKS',           
OMS_ID              STRING COMMENT 'OMS_ID',            
SHORT_NAME          STRING COMMENT 'SHORT_NAME',        
DISTRICT_CODE       STRING COMMENT 'DISTRICT_CODE'      
     
)
COMMENT ''
PARTITIONED BY (MONTH_PART STRING COMMENT '月份分区',
DAY_PART STRING COMMENT '日期分区')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS RCFILE;