CREATE TABLE ODS_PUB_TAB_DEPT_TYPE_D   (
ACCT_MONTH      STRING COMMENT 'ACCT_MONTH',  
DAY_ID          STRING COMMENT 'DAY_ID',      
DEPT_TYPE       STRING COMMENT 'DEPT_TYPE',   
NAME            STRING COMMENT 'NAME',        
DEPT_PTYPE      STRING COMMENT 'DEPT_PTYPE',  
DEPT_CTYPE      STRING COMMENT 'DEPT_CTYPE',  
BUSIFEE_TYPE    STRING COMMENT 'BUSIFEE_TYPE',
RIGHT_TYPE      STRING COMMENT 'RIGHT_TYPE'   
   
)
COMMENT ''
PARTITIONED BY (MONTH_PART STRING COMMENT '月份分区',
DAY_PART STRING COMMENT '日期分区')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS RCFILE;