CREATE TABLE ODS_PUB_TAB_DEVELOP_ORG_D  (
ACCT_MONTH  STRING COMMENT 'ACCT_MONTH',
DAY_ID      STRING COMMENT 'DAY_ID',    
ORG_ID      STRING COMMENT 'ORG_ID',    
ORG_NAME    STRING COMMENT 'ORG_NAME',  
AREAID      STRING COMMENT 'AREAID',    
ORG_CODE    STRING COMMENT 'ORG_CODE',  
BILL_CODE   STRING COMMENT 'BILL_CODE'  
 
)
COMMENT ''
PARTITIONED BY (MONTH_PART STRING COMMENT '月份分区',
DAY_PART STRING COMMENT '日期分区')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS RCFILE;