CREATE TABLE ODS_BUS_BUSINESS_AREA_D  (
ACCT_MONTH               STRING COMMENT  'ACCT_MONTH',             
DAY_ID                   STRING COMMENT  'DAY_ID',                 
BUSINESS_AREA_ID         STRING COMMENT  'BUSINESS_AREA_ID',       
NAME                     STRING COMMENT  'NAME',                   
ORGANIZE_ID              STRING COMMENT  'ORGANIZE_ID',            
PARENT_BUSINESS_AREA_ID  STRING COMMENT  'PARENT_BUSINESS_AREA_ID',
STATE                    STRING COMMENT  'STATE',                  
REMARKS                  STRING COMMENT  'REMARKS',                
COUNTYID                 STRING COMMENT  'COUNTYID'                
 
)
COMMENT ''
PARTITIONED BY (MONTH_PART STRING COMMENT '月份分区',
DAY_PART STRING COMMENT '日期分区')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS RCFILE;