CREATE TABLE ODS_CUS_INDUSTRY_KIND_D (
ACCT_MONTH          STRING COMMENT 'ACCT_MONTH',        
DAY_ID              STRING COMMENT 'DAY_ID',            
INDUSTRY_TYPE_ID    STRING COMMENT 'INDUSTRY_TYPE_ID',  
INDUSTRY_KIND_ID    STRING COMMENT 'INDUSTRY_KIND_ID',  
INDUSTRY_KIND_NAME  STRING COMMENT 'INDUSTRY_KIND_NAME',
INSERT_DATE         STRING COMMENT 'INSERT_DATE',       
STAUTS              STRING COMMENT 'STAUTS',            
REMARK              STRING COMMENT 'REMARK'             
       
)
COMMENT ''
PARTITIONED BY (MONTH_PART STRING COMMENT '月份分区',
DAY_PART STRING COMMENT '日期分区')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS RCFILE;