CREATE TABLE ODS_BUS_BMS_SUBJECT_DEF_D  (
ACCT_MONTH          STRING COMMENT 'ACCT_MONTH',       
DAY_ID              STRING COMMENT 'DAY_ID',           
SUBJECT_ID          STRING COMMENT 'SUBJECT_ID',       
SUBJECT_NAME        STRING COMMENT 'SUBJECT_NAME',     
SUBJECT_TYPE        STRING COMMENT 'SUBJECT_TYPE',     
SUBJECT_SUBTYPE     STRING COMMENT 'SUBJECT_SUBTYPE',  
SUBJECT_TYPE_DESC   STRING COMMENT 'SUBJECT_TYPE_DESC',
TRANS_FLAG          STRING COMMENT 'TRANS_FLAG',       
ACC_SUBJECT_ID      STRING COMMENT 'ACC_SUBJECT_ID'    
 
)
COMMENT ''
PARTITIONED BY (MONTH_PART STRING COMMENT '月份分区',
DAY_PART STRING COMMENT '日期分区')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS RCFILE;