CREATE TABLE ODS_BUS_BUSINESS_OPERATE_D   (
ACCT_MONTH            STRING COMMENT 'ACCT_MONTH',        
DAY_ID                STRING COMMENT 'DAY_ID',            
ID                    STRING COMMENT 'ID',                
BUSINESS_ID           STRING COMMENT 'BUSINESS_ID',       
BUSINESS_KIND         STRING COMMENT 'BUSINESS_KIND',     
SO_VIEW               STRING COMMENT 'SO_VIEW',           
OPERATE_TYPE          STRING COMMENT 'OPERATE_TYPE',      
QUERY_FLAG            STRING COMMENT 'QUERY_FLAG',        
DEL_FLAG              STRING COMMENT 'DEL_FLAG',          
USER_STATE_CONFIG     STRING COMMENT 'USER_STATE_CONFIG', 
COMMIT_STATE          STRING COMMENT 'COMMIT_STATE',      
SO_STATE              STRING COMMENT 'SO_STATE',          
FEE_CHECK             STRING COMMENT 'FEE_CHECK',         
EXTEND_FLAG           STRING COMMENT 'EXTEND_FLAG',       
STATE                 STRING COMMENT 'STATE',             
REMARKS               STRING COMMENT 'REMARKS',           
REMOVE_BUSINESS_ID    STRING COMMENT 'REMOVE_BUSINESS_ID',
QC_FLAG               STRING COMMENT 'QC_FLAG',           
IS_STATE_UPDATE       STRING COMMENT 'IS_STATE_UPDATE',   
FLOW_TEMPLATE_CODE    STRING COMMENT 'FLOW_TEMPLATE_CODE',
EVENT_CODE            STRING COMMENT 'EVENT_CODE'         
     
)
COMMENT ''
PARTITIONED BY (MONTH_PART STRING COMMENT '月份分区',
DAY_PART STRING COMMENT '日期分区')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS RCFILE;