CREATE TABLE ODS_PRD_PM_PE_VALUE_D  (
ACCT_MONTH         STRING COMMENT 'ACCT_MONTH',
DAY_ID             STRING COMMENT 'DAY_ID',    
PE_ID              STRING COMMENT 'PE_ID',     
PE_VALUE           STRING COMMENT 'PE_VALUE',  
PE_VALUE_DESC      STRING COMMENT 'PE_VALUE_DESC'
   
)
COMMENT ''
PARTITIONED BY (MONTH_PART STRING COMMENT '月份分区',
DAY_PART STRING COMMENT '日期分区')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS RCFILE;