CREATE TABLE ODS_PUB_SVC_FEATURE_D  (
ACCT_MONTH               STRING COMMENT 'ACCT_MONTH',            
DAY_ID                   STRING COMMENT 'DAY_ID',                
SVC_TYPE                 STRING COMMENT 'SVC_TYPE',              
SVC_FEAT_NAME            STRING COMMENT 'SVC_FEAT_NAME',         
SVC_FEAT_LEVEL           STRING COMMENT 'SVC_FEAT_LEVEL',        
PE_ID                    STRING COMMENT 'PE_ID',                 
SVC_FEAT_DESC            STRING COMMENT 'SVC_FEAT_DESC',         
SVC_FEAT_VALUE_MIN       STRING COMMENT 'SVC_FEAT_VALUE_MIN',    
SVC_FEAT_VALUE_MAX       STRING COMMENT 'SVC_FEAT_VALUE_MAX',    
SVC_FEAT_VALUE_DEFAULT   STRING COMMENT 'SVC_FEAT_VALUE_DEFAULT',
SVC_FEAT_UNIT            STRING COMMENT 'SVC_FEAT_UNIT',         
SVC_FEAT_TYPE            STRING COMMENT 'SVC_FEAT_TYPE',         
SVC_FEAT_STATISTIC       STRING COMMENT 'SVC_FEAT_STATISTIC',    
SVC_FEAT_ORDER           STRING COMMENT 'SVC_FEAT_ORDER',        
SVC_FEAT_CATEGORY        STRING COMMENT 'SVC_FEAT_CATEGORY',     
SVC_FEAT_PARENT          STRING COMMENT 'SVC_FEAT_PARENT'     
)
COMMENT ''
PARTITIONED BY (MONTH_PART STRING COMMENT '月份分区',
DAY_PART STRING COMMENT '日期分区')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS RCFILE;