CREATE TABLE ODS_PUB_SYS_PARAMETERS_D (
ACCT_MONTH      STRING COMMENT 'ACCT_MONTH',    
DAY_ID          STRING COMMENT 'DAY_ID',        
REGION_ID       STRING COMMENT 'REGION_ID',     
SVC_TYPE        STRING COMMENT 'SVC_TYPE',      
PARAM_ID        STRING COMMENT 'PARAM_ID',      
PARAM_DATATYPE  STRING COMMENT 'PARAM_DATATYPE',
PARAM_VALUE     STRING COMMENT 'PARAM_VALUE',   
PARAM_DESC      STRING COMMENT 'PARAM_DESC',    
OPER_DATE       STRING COMMENT 'OPER_DATE',     
OPER_ID         STRING COMMENT 'OPER_ID',       
PARAM_TYPE      STRING COMMENT 'PARAM_TYPE'        
)
COMMENT ''
PARTITIONED BY (MONTH_PART STRING COMMENT '月份分区',
DAY_PART STRING COMMENT '日期分区')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS RCFILE;