CREATE TABLE ODS_PUB_TAB_DEPT_PTYPE_D  (
ACCT_MONTH   STRING COMMENT 'ACCT_MONTH',
DAY_ID       STRING COMMENT 'DAY_ID',    
DEPT_PTYPE   STRING COMMENT 'DEPT_PTYPE',
NAME         STRING COMMENT 'NAME'       
)
COMMENT ''
PARTITIONED BY (MONTH_PART STRING COMMENT '月份分区',
DAY_PART STRING COMMENT '日期分区')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS RCFILE;