CREATE TABLE ODS_PUB_SVC_FEATVAL_D  (
ACCT_MONTH      STRING COMMENT 'ACCT_MONTH',    
DAY_ID          STRING COMMENT 'DAY_ID',        
SVC_TYPE        STRING COMMENT 'SVC_TYPE',      
SVC_FEAT_NAME   STRING COMMENT 'SVC_FEAT_NAME', 
SVC_FEAT_VALUE  STRING COMMENT 'SVC_FEAT_VALUE',
SVC_FEAT_VDESC  STRING COMMENT 'SVC_FEAT_VDESC'      
)
COMMENT ''
PARTITIONED BY (MONTH_PART STRING COMMENT '月份分区',
DAY_PART STRING COMMENT '日期分区')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS RCFILE;