CREATE TABLE ODS_CHL_TYPE_DEFINE_D   (
ACCT_MONTH             STRING COMMENT 'ACCT_MONTH',         
DAY_ID                 STRING COMMENT 'DAY_ID',             
CHANNEL_TYPE           STRING COMMENT 'CHANNEL_TYPE',       
TYPE_NAME              STRING COMMENT 'TYPE_NAME',          
ZB_CHANNEL_TYPE        STRING COMMENT 'ZB_CHANNEL_TYPE',    
ZB_TYPE_NAME           STRING COMMENT 'ZB_TYPE_NAME',       
ZB_CHANNEL_SUB_TYPE    STRING COMMENT 'ZB_CHANNEL_SUB_TYPE',
ZB_CHANNEL_SUB_NAME    STRING COMMENT 'ZB_CHANNEL_SUB_NAME',
CHANNEL_SUB_TYPE       STRING COMMENT 'CHANNEL_SUB_TYPE',   
SUB_TYPE_NAME          STRING COMMENT 'SUB_TYPE_NAME'       
)
COMMENT ''
PARTITIONED BY (MONTH_PART STRING COMMENT '月份分区',
DAY_PART STRING COMMENT '日期分区')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS RCFILE;