hive  -e  "
use ods;
create table   ODS_CDR_OCS_SMS_D   
(

    ACCT_MONTH             string     comment  'ACCT_MONTH',
    DAY_ID                 string     comment  'DAY_ID',
    SYS_SVC_TYPE           string     comment   'SYS_SVC_TYPE',
    MDN                    string     comment   'MDN',
    CALL_TYPE              string     comment   'CALL_TYPE',
    HOME_AREA              string     comment   'HOME_AREA',
    START_TIME             string     comment   'START_TIME',
    OPP_PARTY              string     comment   'OPP_PARTY',
    OPP_NUMBER             string     comment   'OPP_NUMBER',
    SP_CODE                string     comment   'SP_CODE',
    SP_SMG                 string     comment   'SP_SMG',
    ACCESS_CODE            string     comment   'ACCESS_CODE',
    SERVICE_CODE           string     comment    'SERVICE_CODE',
    LANG_TYPE              string     comment    'LANG_TYPE',
    SV_TYPE                string     comment    'SV_TYPE',
    SVC_EX                 string     comment    'SVC_EX',
    MSG_TYPE               string     comment    'MSG_TYPE',
    MSG_LENGTH             string     comment    'MSG_LENGTH',
    STOP_CAUSE             string     comment    'STOP_CAUSE',
    NICE                   string     comment    'NICE',
    SMG_CODE               string     comment    'SMG_CODE',
    USER_TYPE              string     comment    'USER_TYPE',
    CFEE1                  float      comment    'CFEE1',
    IFEE1                  float      comment    'IFEE1',
    PLATFORM_ID            string     comment    'PLATFORM_ID',
    RECORD_NO              string     comment    'RECORD_NO',
    SMG_IN                 string     comment    'SMG_IN',
    SMG_OUT                string     comment    'SMG_OUT',
    ISRATE                 string     comment    'ISRATE',
    FILE_TYPE              string     comment    'FILE_TYPE',
    FILE_NO                string     comment    'FILE_NO',
    SERVICE_NUMBER         string     comment    'SERVICE_NUMBER',
    PART_ID                string     comment    'PART_ID',
    ACCT_ID                string     comment    'ACCT_ID',
    SUB_ID                 string     comment    'SUB_ID',
    SVC_TYPE               string     comment    'SVC_TYPE',
    REGION_ID              string     comment    'REGION_ID',
    USAGE_TYPE             string     comment    'USAGE_TYPE',
    USAGE_CASE             string     comment    'USAGE_CASE',
    USAGE_CLASS            string     comment    'USAGE_CLASS',
    CLASS_OF_SRV_CODE      string     comment    'CLASS_OF_SRV_CODE',
    CFEE                   float      comment    'CFEE',
    LFEE                   float      comment    'LFEE',
    IFEE                   float      comment    'IFEE',
    MFEE                   float      comment    'MFEE',
    TFEE                   float      comment    'TFEE',
    DIS_CFEE               float      comment    'DIS_CFEE',
    DIS_LFEE               float      comment    'DIS_LFEE',
    DIS_IFEE               float      comment    'DIS_IFEE',
    CFEE_TIMES             float      comment    'CFEE_TIMES',
    LFEE_TIMES             float      comment    'LFEE_TIMES',
    IFEE_TIMES             float      comment    'IFEE_TIMES',
    MFEE_TIMES             float      comment     'MFEE_TIMES',
    TFEE_TIMES             float      comment     'TFEE_TIMES',
    CFEE_SUBJECT           string     comment     'CFEE_SUBJECT',
    LFEE_SUBJECT           string     comment     'LFEE_SUBJECT',
    IFEE_SUBJECT           string     comment     'IFEE_SUBJECT',
    MFEE_SUBJECT           string     comment     'MFEE_SUBJECT',
    TFEE_SUBJECT           string     comment     'TFEE_SUBJECT',
    PACKAGE_ID             string     comment     'PACKAGE_ID',
    PRODUCT_CLASS          string     comment     'PRODUCT_CLASS',
    RAW_FILENAME           string     comment     'RAW_FILENAME',
    LATE_LINK              string     comment     'LATE_LINK',
    CAL_TIME               string     comment     'CAL_TIME',
    AUDI_STR               string     comment     'AUDI_STR',
    VARIAN_STR             string     comment     'VARIAN_STR',
    RERATE_CNT             int        comment     'RERATE_CNT',
    TIMESTAMP              string     comment     'TIMESTAMP',
    END_TIME               string     comment      'END_TIME',
    OCS_SERIAL_NO          string     comment      'OCS_SERIAL_NO',
    HOST_ID                string     comment       'HOST_ID',
    OCS_SRV_TYPE           string     comment       'OCS_SRV_TYPE',
    CUST_ID                string     comment       'CUST_ID',
    BRAND                  string     comment       'BRAND',
    RAW_HOST               string     comment       'RAW_HOST',
    BALANCE_INFO           string     comment       'BALANCE_INFO',
    BEARER_CAPABILITY      string     comment       'BEARER_CAPABILITY',
    CALLING_PARTY          string     comment        'CALLING_PARTY',
    CALLED_PARTY           string     comment        'CALLED_PARTY',
    RAW_CALLING_PARTY      string     comment        'RAW_CALLING_PARTY',
    RAW_CALLED_PARTY       string     comment         'RAW_CALLED_PARTY',
    BALANCE_VALUE          float      comment         'BALANCE_VALUE',
    EXP_DATE               string     comment         'EXP_DATE',
    TOTAL_USED             int        comment         'TOTAL_USED',
    CASH_USED              int        comment         'CASH_USED',
    GIFT_USED              int        comment         'GIFT_USED',
    INSERT_DATE            string     comment         'INSERT_DATE'
)
comment '[MASTER_FIELD:B域,LEVEL:ODS层,DATA_FIELD:详单域,DATASUB_FIELD:ODS_CDR_OCS_SMS_D]'
PARTITIONED BY (MONTH_PART STRING comment '月份分区',DAY_PART STRING comment '日期分区')
ROW FORMAT DELIMITED FIELDS TERMINATED BY '\001' 
STORED AS RCFILE;
"